seed:
  image: mfdata/seedproject
  volumes:
    - ./../app:/home/current/app
  command: npm start #top -b#
  links:
    - postgres
    - eventstore
  environment:
    DEBUG: true
    NODE_ENV: development
    APPLICATION_NAME: seed
postgres:
  image: postgres
  environment:
    - LANG=en_US.UTF-8
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=methodfitness
  ports:
    - 5432:5432
eventstore:
  image: adbrowne/eventstore
  command: ./run-node.sh --ext-http-prefixes=http://*:2113/ --ext-ip=0.0.0.0 --db /data/db --log /data/logs --stats-period-sec=300 --run-projections=all
